### ISSUE TITLE
[Bug] No longer can connect to server with Terrastorage installed using vanilla client

### ISSUE THREAD

**Issue by LydiaLambda** [TimVincii/Terrastorage#15] opened 2024-12-15 16:45 UTC
### What happened?

As of the latest update for 1.21.4, it is no longer possible to connect to a modded Fabric server with Terrastorage installed, using a vanilla client.

This was possible in the previous version. Though even then, some functions caused vanilla players to be disconnected.

Expected that vanilla clients would still be able to connect to modded server.

### Terrastorage Version

1.2.1+1.21.4

### Fabric API Version

0.112.0+1.21.4 AND/OR 0.111.0+1.21.4

### Minecraft Version

1.21.4

### Relevant Log Output

```shell
lost connection: This server requires Fabric Loader and Fabric API installed on your client!
The following registry entry namespaces may be related:

terrastorage


Contact the server's administrator for more information!
```

### Other Mods

```shell
none
```

**Comment by TimVincii** [comment] 2024-12-15 20:10
Hi! thanks for taking time to submit this bug report.

I was never aware of these kind of issues, and I completely agree that vanilla clients shouldn't be blocked from modded servers because of Terrastorage.

I'd love to work on this as of this moment, but unfortunately I'm not home until Friday.

In the meantime, you mentioned there were other functions that caused Vanilla players to disconnect, can you provide more details about that? It could help with understanding the underlying issue behind this bug.

**Comment by LydiaLambda** [comment] 2024-12-15 21:29
Hi!

Yeah for sure! I can try and explain some things I've noticed. I should have old server log files / screenshots as well that I could provide if you need in the future.

I think it may mostly relate to the 'favourite' function?

One thing I encountered was that if you joined the server with Terrastorage installed, and favourited any items. Then left the server, and re-joined without Terrastoreage - you would not be able to re-join. This was fixable by removing Terrastorage from the server and then having the vanilla player join, then re-adding mod to the server, then the vanilla player could connect. 
Strangely this issue also happened for one player who only ever used vanilla client, but was fixable in the same way i.e. having her load in without the server mod at least once after she couldn't connect. It may have happened to her after I was playing and had favourited items, but I'm still not 100% sure what caused it.

We also eventually accidentally discovered a cause of previously seemingly random disconnects for her (her playing vanilla, myself with mods). She would be instantly kicked and unable to rejoin the instant I moved a favourited item from inside my inventory to my hotbar. As soon as I moved the item from hotbar back into inventory, or un-favourited it, then she would instantly be able to connect once again.

Error messages generally showed netty server io errors, failure to decode packet clientbound set_equipment, clientbound minecraft disconnect, etc... I'd have to dig around logs for specifics

Thank you for taking the time to respond and for all your work on this mod! I've been using other inventory management mods since the latest update now, and I have to say, yours is by far my favourite, definitely the most elegant and fully featured. I was playing with a friend and we were discussing how we missed Terraria's inventory features, were wishing for a mod that did it, so I searched, and lo and behold, you already made it happen! :D

Best of luck with your studies!

**Comment by TimVincii** [comment] 2024-12-16 20:25
Hey again, thanks for providing such an amazing level of detail, and thank you so much for the kind words, it truly means the world to me!

I'll do my best to address this issue the second I'm back home on Friday, and I'll make sure to update you here with hopefully promising news.

Have a fantastic day!

**Comment by TimVincii** [comment] 2024-12-22 20:14
Hey again! I worked on this during the weekend but unfortunately I wasn't able to finish in time, I do have some news though:

I tested out many cases in which a vanilla client joins a server with Terrastorage and this is what my tests concluded:
### Minecraft 1.21.1 and below:
Vanilla clients are able to join, but the server can send packets with the `favorite_item` data component to them, causing them to be disconnected. This is exactly what happened with the set_equipment packet you mentioned.

### Minecraft 1.21.2 and above:
As of 1.21.2 I wasn't able to join a server with Terrastorage from a vanilla client, seems like as of this version, Fabric is much more strict with enforcing mods to be installed on both sides if the server side registers anything, even the simple boolean data component that Terrastorage uses to mark favorite items.

I did find a way of solving the issue for versions 1.21.1 and below, but I'll need some more time to research what can be done for the newer versions.
I'll do my best to see if I can figure something out during the weekend but I'll already say that I might not be able to produce a solid solution. 

As much as I don't want vanilla players to be blocked from joining servers, Terrastorage was designed to be a client and server sided mod, and I simply don't have time to start working on complex workarounds due to Fabric becoming more strict with certain aspects.

With that all said, I wish you a great day, and I'll update on Friday/Saturday.

**Comment by TimVincii** [comment] 2024-12-29 05:44
Hey again,

I worked on this during the weekend, but unfortunately I couldn't find a solution.

Once Terrastorage registers a data component type on the server side, Fabric requires all clients to be able to identify that component in order to join, at least as of 1.21.2.

Since the custom component is the only culprit of this issue, I tried working on a toggle for the Item Favoriting feature, but it proved to be problematic:
If the server stopped registering the component while players still had favorite items in their inventory, they would be locked from joining. A potential solution would be to iterate over every player's inventory and unfavorite all items, but I didn't have time to research whether its a plausible solution based on the performance impact it could create.

I do believe a toggle might provide at least a bit of a solution for servers looking to support vanilla clients, so I'll work on that when I can, but for now, I'll be closing this issue.

Thank you again for your time, cooperation, and kind words, truly means a lot to me.
Have a marvelous day!

**Closed by TimVincii** 2024-12-29 05:44 UTC
Labels: bug
